### ISSUE TITLE
set alarm unit

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/PandroidPackage#1]
Many visually impaired users are facing issues while they want to set their alarm. Sure. Somebod ycan tell Me. Blinddroid alarm is on GOogle Play. GOogle assitant may be allow that. Antelly voice assistant may allow it too. But to be honest. Why we could not simply have fully accessible simple app to setup alarm? By typing time in hours and minutes and combobox to set The day of alarm? I have many experience with Android 8 and newer. It is possible to force The OS to refresh every specified app in background. And there is even Pascal code to enforce ignore battery optimisations. When user will combine run in background feature and by enforcing ignore battery optimisations alarm will be refreshed automatically and will be activated automatically at A desired time by using build in Android alarm manager.
It would be interesting to have this little unit available to set alarm.

**Comment by zeljkoc** [comment]
does something like this fit:
Android AlarmManager Broadcast Receiver And Service
https://www.journaldev.com/27681/android-alarmmanager-broadcast-receiver-and-service
