### ISSUE TITLE
items.add and gridview do not support Czech unicode characters in strings

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/PandroidPackage#2]
I have found out that items.add command is not able to correctly write Czech Unicode characters inside The table. Some Czech characters are misinterpreted as Grek mathematical symbols, Etc.

Other Pandroid units commands support Czech characters perfectly including Textview, button, azcforms.inc unit. Do yout hink, that it could be done something with items.add procedure so it will support Czech characters correctly? Or is it build in Android APi iesue which it is impossible to solve in Pascal?
Thank you very much for yours advices.

**Comment by zeljkoc** [comment]
Try to load from TEditView, dynamically in operation.
or send me an example

**Comment by JanuszChmiel** [comment]
Here is example.
Based on yours gridview sample code.

**Comment by JanuszChmiel** [comment]
Oh I Am very sorry. The probelm have been caused by The Lazarus Ide, which
have not used UTF8 unicode encoding. Since characters are misinterpreted
even on Akelpad on Windows, so there was problem related to encoding. SO I
will have to save from Aelpad to get UTF8 encoding.
You can close The issue.
