### ISSUE TITLE
Please consider to add hint text editable field support to azcforms unit

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/PandroidPackage#8]
I have started to develop app to allow Me to train The seniors, who are sufrering with mental diseases and memory issues. I have started to recode textual material which consists of several verbal based quizes. I have little and light weight Samsung GT-B5330 with build in Querty keyboard. I will be able to control seniors answers by using my new app written by using Pandroid units and PPCJVM. The only one thing what I need is to have The opportunity to create 45 or more edit boxes and every of those editboxes should support special Android object property, hint. If editbox support hint text, my screen reader will read it immediately when I swipe with my fingertip. The only one issue is, if is it possible to add 45 Editboxes. No matter, if GUi will not look nice, it is only necessary that app will be able to create so many editboxes, not only 25 for example. Because when I have tried to add buttons before I have started to use azcforms, Android APIS allowed Me only to add 25 buttons. But thanks to yours algorithm build in to azcforms, it is possible to add many many buttons. The problem is, how complex would be to add hint to every edit box. And if it will be possible to monitor those all 45 editable boxes for changes. I want to have result immediately when I will type The right word to one of 45 editboxes to save finger tip movement and time. I will play nice sound when good answer will be typed and I will be using bass.so native library to play sound, because Media player API is making chaos on this phone, it is very probably because there is only 512 MB of RAM but C bass.so native library is working as it should without memory leaks. Thank you for yours programmers help.

**Comment by zeljkoc** [comment]
To help you I have to imagine what it looks like.
Can someone help you and show me which fields you should and how the
question and answer would work.
Would the answers be yes or no or ...

Best regards,
Zeljko

sub, 28. kol 2021. u 16:55 JanuszChmiel ***@***.***> napisao
je:

**Comment by JanuszChmiel** [comment]
GUI would create 45 edit fields.
Every of those edit field should contain hint text for example by using The following function.

myedittext.setHint("hint text")
The most complex thing. How to force ANdroid APIS to display so many edit boxes no matter which screen syze will be used. And how to create The code, which wwould be able to monitor every of those edit boxes in background for The right answer.
Verbal tests are based on tasks such as.
Write The right names of every Czech town name. Names contain randomly placed sentences. I do not want to use texttview because I need to have fast system. Swipe with one finger to jump between every editable fields. This is done by Talkback screen reader. And I can type with build in querty hardware keyboard.
Ideal solution would be, that if user would complete The right answer to one of editbox, this edit box could change its state to read only. So it will indicate, that The right answer have been given.
I believe, that it is possible to achieve by using Android APIS and Pascal key words.
I can not use RFO Basic or other Basics on The net. It allocates too much RAM. And Java is not easy for Me so I love Pascal so much. I will also try to write some code here so I will show you that I AM really do my best to be independent programmer.

**Comment by JanuszChmiel** [comment]
Oh, I have read article about Java programming in Android. And I would had to Set the hint to the TextInputLayout instead.
So I can not use TEdit but I would had to use TextInputLayout .
I will analyse my loving AndroidR25 Pascal header files for this class, because I do not thing, that TextInputLayout  have been added to AzcControls unit.
It will be big adventure.

**Comment by zeljkoc** [comment]
DemoSQLite
This possibility exists for fields defined in SQLite:
https://github.com/zeljkoc/PandroidPackage/tree/master/Demos/DemoSQLite

uses DB;

TDBGridViewLayout



uto, 31. kol 2021. u 15:28 JanuszChmiel ***@***.***> napisao
je:

**Comment by JanuszChmiel** [comment]
Oh, it is wonderful approach, really.      GridView.setNumColumns(1);
     Adapter.CursorDataSet.TableName := 'MjestoPopisa';

And GridView is so wonderful object for visuallyimpaired screen reader users. Thank you for yours tip. I will try example and I will test it.

**Comment by JanuszChmiel** [comment]
And what about using
procedure THederForms.AddButtonEditText(aButtonEditText: TButtonEditText; aButtonID: jint);
Because if I Am understanding this procedure from azcforms unit well. It creates buttons with textual descriptions and if user click on one of created buttons, it creates editable field. I will try to play with this procedure. I have even found out, that yours bundle is more than ideal for visually impaired programmers. It is thanks to yours 100 % Android APIS knowledge. You have collected The best possible possibilities  to create GUi without objectt position values and with no need to use .xml files. Yours approavch is ideal that it is possible to specify many GUI elements and GUi contain special scrollable element so sighted users can scroll and look is still looking very nice.
