### ISSUE TITLE
procedure which allow to create 45 or more editable fields

### ISSUE THREAD

**Issue by JanuszChmiel** [zeljkoc/PandroidPackage#9]
I have done my best to find The solution myself.
What do I need?
I need The similar procedure for editable fields creation like
  layout.addButton(Self, 10, 'Stop');
Procedure addbutton allow every one to add for example 100 or 200 buttons. It is possible to scroll so even sighted majority can be satisfied.
Please, is it possible to create The similar procedure to create so many edit fields? I also need to react on every field change.
Why do I need such think?
Because with my little portable mobile phone with build in QUERTY keyboard I could write words and routine could evaluate right answer in time.
Is it possible to achieve such goal, or Android APi functions do not allow developers to create so many editable fields?
Your procedure from azcforms.pas
Please could you write a procedure for this purpose? Or unfortunately, Android APi do not allow to create such type of GUI.
I do not know, if procedure
    procedure AddButtonEditText(aButtonEditText: TButtonEditText; aButtonID: jint); 
Can create for example 45 editable fields or more.
Thank you for yours help.

**Comment by zeljkoc** [comment]
Perhaps this example can help:
https://github.com/zeljkoc/pandroid/tree/master/example/DemoScrollButton

ned, 19. ruj 2021. u 15:31 JanuszChmiel ***@***.***> napisao
je:

**Comment by JanuszChmiel** [comment]
Thank you very much for yours tip, I will try to test it. Fortunately for Me, Android API functions allow many GUI variants and even visually impaired developers can have a benefits from using of this APi functions.
